services:
  postgis:
    image: postgis/postgis:15-3.3
    env_file:
      - ./secrets/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  database:
