services:
  postgis:
    build:
      context: .
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
      - ./QField_sample_data/insert_sample_data.sql:/docker-entrypoint-initdb.d/02-insert_sample_data.sql
volumes:
  database:
